### ISSUE TITLE
The navMap cannnot be rendered when using floodmap rendering

### ISSUE THREAD

**Issue by lj-cug** [SahebSh/flood-pedestrian-simulator#1]
Dear Sir,
When i render the navMap, Pedestrian and Floodmap in glfw instead of glut, the NavMap cannot be rendered? i don't know why?
Yours,
Li Jian

**Comment by SahebSh** [comment]
Dear Li Jian, 

Thank you for your interest in trying the flood-pedestrian simulator. 

Unfortunately I am not quite sure what the issue might be. However, I know that there are limitations in using FLAME-GPU which uses glut threading functions. 

Would you be able to use glut instead? 

Could you please let us know if you find a solution to your issue? 

Feel free to stay in touch. 

Kind regards
Saheb

**Comment by lj-cug** [comment]
These days I read the code, and try to use ImGUI and glfw3 to visualize the flood-pedestrian simulation results.
Now I cannot project the rendered window into a glfw window, which means the interactive visualisation cannot be controlled using my mouse. It's like this:
![run_Flood](https://github.com/user-attachments/assets/03f6abe4-f9e3-4646-8bdb-353bd978138e)
Another interactive visualisation tool called FIP, which use ImGUI and glfw3. The rendered window can be controlled interactively. It's like this:
![run_FIP](https://github.com/user-attachments/assets/bce9bd03-e4dd-41ea-82c6-6054882f953c)

**Comment by lj-cug** [comment]
By the way, I found the shaded used in flood-pedestrian simulator is old. I cannot control the window using my own defined model, view, projection. flood-pedestrian simulator used "gl_ModelViewProjectionMatrix" that is not used in new version GLSL. But I'm not familar with Shader language.
